<?php

namespace Database\Seeders;

use App\Models\Municipalidades;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MunicipalidadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Municipalidades::create(['nombre' => 'Arica', 'codigo'=>'15101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Camarones', 'codigo'=>'15102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Putre', 'codigo'=>'15201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'General Lagos', 'codigo'=>'15202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Iquique', 'codigo'=>'01101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Camiña', 'codigo'=>'01402', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Colchane', 'codigo'=>'01403', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Huara', 'codigo'=>'01404', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pica', 'codigo'=>'01405', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pozo Almonte', 'codigo'=>'01401', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Alto Hospicio', 'codigo'=>'01107', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Antofagasta', 'codigo'=>'02101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Mejillones', 'codigo'=>'02102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Sierra Gorda', 'codigo'=>'02103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Taltal', 'codigo'=>'02104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Calama', 'codigo'=>'02201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Ollagüe', 'codigo'=>'02202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Pedro de Atacama', 'codigo'=>'02203', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Tocopilla', 'codigo'=>'02301', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'María Elena', 'codigo'=>'02302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Copiapó', 'codigo'=>'03101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Caldera', 'codigo'=>'03102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Tierra Amarilla', 'codigo'=>'03103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Chañaral', 'codigo'=>'03201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Diego de Almagro', 'codigo'=>'03202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Vallenar', 'codigo'=>'03301', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Alto del Carmen', 'codigo'=>'03302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Freirina', 'codigo'=>'03303', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Huasco', 'codigo'=>'03304', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'La Serena', 'codigo'=>'04101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Coquimbo', 'codigo'=>'04102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Andacollo', 'codigo'=>'04103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'La Higuera', 'codigo'=>'04104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Paiguano', 'codigo'=>'04105', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Vicuña', 'codigo'=>'04106', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Illapel', 'codigo'=>'04201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Canela', 'codigo'=>'04202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Los Vilos', 'codigo'=>'04203', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Salamanca', 'codigo'=>'04204', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Ovalle', 'codigo'=>'04301', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Combarbalá', 'codigo'=>'04302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Monte Patria', 'codigo'=>'04303', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Punitaqui', 'codigo'=>'04304', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Río Hurtado', 'codigo'=>'04305', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Valparaíso', 'codigo'=>'05101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Casablanca', 'codigo'=>'05102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Concón', 'codigo'=>'05103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Juan Fernández', 'codigo'=>'05104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Puchuncaví', 'codigo'=>'05105', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quilpué', 'codigo'=>'05801', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quintero', 'codigo'=>'05107', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Villa Alemana', 'codigo'=>'05804', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Viña del Mar', 'codigo'=>'05109', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Isla  de Pascua', 'codigo'=>'05201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Los Andes', 'codigo'=>'05301', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Calle Larga', 'codigo'=>'05302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Rinconada', 'codigo'=>'05303', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Esteban', 'codigo'=>'05304', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'La Ligua', 'codigo'=>'05401', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cabildo', 'codigo'=>'05402', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Papudo', 'codigo'=>'05403', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Petorca', 'codigo'=>'05404', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Zapallar', 'codigo'=>'05405', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quillota', 'codigo'=>'05501', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Calera', 'codigo'=>'05502', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Hijuelas', 'codigo'=>'05503', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'La Cruz', 'codigo'=>'05504', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Limache', 'codigo'=>'05802', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Nogales', 'codigo'=>'05506', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Olmué', 'codigo'=>'05803', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Antonio', 'codigo'=>'05601', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Algarrobo', 'codigo'=>'05602', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cartagena', 'codigo'=>'05603', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'El Quisco', 'codigo'=>'05604', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'El Tabo', 'codigo'=>'05605', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Santo Domingo', 'codigo'=>'05606', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Felipe', 'codigo'=>'05701', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Catemu', 'codigo'=>'05702', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Llaillay', 'codigo'=>'05703', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Panquehue', 'codigo'=>'05704', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Putaendo', 'codigo'=>'05705', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Santa María', 'codigo'=>'05706', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Rancagua', 'codigo'=>'06101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Codegua', 'codigo'=>'06102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Coinco', 'codigo'=>'06103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Coltauco', 'codigo'=>'06104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Doñihue', 'codigo'=>'06105', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Graneros', 'codigo'=>'06106', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Las Cabras', 'codigo'=>'06107', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Machalí', 'codigo'=>'06108', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Malloa', 'codigo'=>'06109', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Mostazal', 'codigo'=>'06110', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Olivar', 'codigo'=>'06111', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Peumo', 'codigo'=>'06112', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pichidegua', 'codigo'=>'06113', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quinta de Tilcoco', 'codigo'=>'06114', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Rengo', 'codigo'=>'06115', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Requínoa', 'codigo'=>'06116', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Vicente', 'codigo'=>'06117', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pichilemu', 'codigo'=>'06201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'La Estrella', 'codigo'=>'06202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Litueche', 'codigo'=>'06203', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Marchihue', 'codigo'=>'06204', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Navidad', 'codigo'=>'06205', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Paredones', 'codigo'=>'06206', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Fernando', 'codigo'=>'06301', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Chépica', 'codigo'=>'06302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Chimbarongo', 'codigo'=>'06303', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lolol', 'codigo'=>'06304', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Nancagua', 'codigo'=>'06305', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Palmilla', 'codigo'=>'06306', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Peralillo', 'codigo'=>'06307', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Placilla', 'codigo'=>'06308', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pumanque', 'codigo'=>'06309', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Santa Cruz', 'codigo'=>'06310', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Talca', 'codigo'=>'07101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Constitución', 'codigo'=>'07102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Curepto', 'codigo'=>'07103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Empedrado', 'codigo'=>'07104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Maule', 'codigo'=>'07105', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pelarco', 'codigo'=>'07106', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pencahue', 'codigo'=>'07107', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Río Claro', 'codigo'=>'07108', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Clemente', 'codigo'=>'07109', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Rafael', 'codigo'=>'07110', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cauquenes', 'codigo'=>'07201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Chanco', 'codigo'=>'07202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pelluhue', 'codigo'=>'07203', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Curicó', 'codigo'=>'07301', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Hualañé', 'codigo'=>'07302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Licantén', 'codigo'=>'07303', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Molina', 'codigo'=>'07304', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Rauco', 'codigo'=>'07305', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Romeral', 'codigo'=>'07306', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Sagrada Familia', 'codigo'=>'07307', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Teno', 'codigo'=>'07308', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Vichuquén', 'codigo'=>'07309', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Linares', 'codigo'=>'07401', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Colbún', 'codigo'=>'07402', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Longaví', 'codigo'=>'07403', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Parral', 'codigo'=>'07404', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Retiro', 'codigo'=>'07405', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Javier', 'codigo'=>'07406', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Villa Alegre', 'codigo'=>'07407', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Yerbas Buenas', 'codigo'=>'07408', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Concepción', 'codigo'=>'08101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Coronel', 'codigo'=>'08102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Chiguayante', 'codigo'=>'08103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Florida', 'codigo'=>'08104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Hualqui', 'codigo'=>'08105', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lota', 'codigo'=>'08106', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Penco', 'codigo'=>'08107', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Pedro de la Paz', 'codigo'=>'08108', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Santa Juana', 'codigo'=>'08109', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Talcahuano', 'codigo'=>'08110', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Tomé', 'codigo'=>'08111', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Hualpén', 'codigo'=>'08112', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lebu', 'codigo'=>'08201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Arauco', 'codigo'=>'08202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cañete', 'codigo'=>'08203', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Contulmo', 'codigo'=>'08204', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Curanilahue', 'codigo'=>'08205', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Los Álamos', 'codigo'=>'08206', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Tirúa', 'codigo'=>'08207', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Los Ángeles', 'codigo'=>'08301', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Antuco', 'codigo'=>'08302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cabrero', 'codigo'=>'08303', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Laja', 'codigo'=>'08304', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Mulchén', 'codigo'=>'08305', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Nacimiento', 'codigo'=>'08306', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Negrete', 'codigo'=>'08307', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quilaco', 'codigo'=>'08308', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quilleco', 'codigo'=>'08309', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Rosendo', 'codigo'=>'08310', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Santa Bárbara', 'codigo'=>'08311', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Tucapel', 'codigo'=>'08312', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Yumbel', 'codigo'=>'08313', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Alto Biobío', 'codigo'=>'08314', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Chillán', 'codigo'=>'16101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Bulnes', 'codigo'=>'16102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cobquecura', 'codigo'=>'16202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Coelemu', 'codigo'=>'16203', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Coihueco', 'codigo'=>'16302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Chillán Viejo', 'codigo'=>'16103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'El Carmen', 'codigo'=>'16104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Ninhue', 'codigo'=>'16204', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Ñiquén', 'codigo'=>'16303', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pemuco', 'codigo'=>'16105', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pinto', 'codigo'=>'16106', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Portezuelo', 'codigo'=>'16205', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quillón', 'codigo'=>'16107', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quirihue', 'codigo'=>'16201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Ránquil', 'codigo'=>'16206', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Carlos', 'codigo'=>'16301', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Fabián', 'codigo'=>'16304', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Ignacio', 'codigo'=>'16108', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Nicolás', 'codigo'=>'16305', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Treguaco', 'codigo'=>'16207', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Yungay', 'codigo'=>'16109', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Temuco', 'codigo'=>'09101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Carahue', 'codigo'=>'09102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cunco', 'codigo'=>'09103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Curarrehue', 'codigo'=>'09104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Freire', 'codigo'=>'09105', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Galvarino', 'codigo'=>'09106', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Gorbea', 'codigo'=>'09107', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lautaro', 'codigo'=>'09108', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Loncoche', 'codigo'=>'09109', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Melipeuco', 'codigo'=>'09110', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Nueva Imperial', 'codigo'=>'09111', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Padre Las Casas', 'codigo'=>'09112', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Perquenco', 'codigo'=>'09113', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pitrufquén', 'codigo'=>'09114', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pucón', 'codigo'=>'09115', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Saavedra', 'codigo'=>'09116', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Teodoro Schmidt', 'codigo'=>'09117', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Toltén', 'codigo'=>'09118', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Vilcún', 'codigo'=>'09119', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Villarrica', 'codigo'=>'09120', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cholchol', 'codigo'=>'09121', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Angol', 'codigo'=>'09201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Collipulli', 'codigo'=>'09202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Curacautín', 'codigo'=>'09203', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Ercilla', 'codigo'=>'09204', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lonquimay', 'codigo'=>'09205', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Los Sauces', 'codigo'=>'09206', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lumaco', 'codigo'=>'09207', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Purén', 'codigo'=>'09208', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Renaico', 'codigo'=>'09209', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Traiguén', 'codigo'=>'09210', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Victoria', 'codigo'=>'09211', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Valdivia', 'codigo'=>'14101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Corral', 'codigo'=>'14102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Futrono', 'codigo'=>'14202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'La Unión', 'codigo'=>'14201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lago Ranco', 'codigo'=>'14203', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lanco', 'codigo'=>'14103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Los Lagos', 'codigo'=>'14104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Máfil', 'codigo'=>'14105', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Mariquina', 'codigo'=>'14106', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Paillaco', 'codigo'=>'14107', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Panguipulli', 'codigo'=>'14108', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Río Bueno', 'codigo'=>'14204', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Puerto Montt', 'codigo'=>'10101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Calbuco', 'codigo'=>'10102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cochamó', 'codigo'=>'10103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Fresia', 'codigo'=>'10104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Frutillar', 'codigo'=>'10105', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Los Muermos', 'codigo'=>'10106', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Llanquihue', 'codigo'=>'10107', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Maullín', 'codigo'=>'10108', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Puerto Varas', 'codigo'=>'10109', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Castro', 'codigo'=>'10201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Ancud', 'codigo'=>'10202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Chonchi', 'codigo'=>'10203', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Curaco de Vélez', 'codigo'=>'10204', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Dalcahue', 'codigo'=>'10205', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Puqueldón', 'codigo'=>'10206', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Queilén', 'codigo'=>'10207', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quellón', 'codigo'=>'10208', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quemchi', 'codigo'=>'10209', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quinchao', 'codigo'=>'10210', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Osorno', 'codigo'=>'10301', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Puerto Octay', 'codigo'=>'10302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Purranque', 'codigo'=>'10303', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Puyehue', 'codigo'=>'10304', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Río Negro', 'codigo'=>'10305', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Juan de la Costa', 'codigo'=>'10306', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Pablo', 'codigo'=>'10307', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Chaitén', 'codigo'=>'10401', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Futaleufú', 'codigo'=>'10402', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Hualaihué', 'codigo'=>'10403', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Palena', 'codigo'=>'10404', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Coihaique', 'codigo'=>'11101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lago Verde', 'codigo'=>'11102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Aisén', 'codigo'=>'11201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cisnes', 'codigo'=>'11202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Guaitecas', 'codigo'=>'11203', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cochrane', 'codigo'=>'11301', 'activo'=>1]);
        Municipalidades::create(['nombre' => "O'Higgins", 'codigo'=>'11302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Tortel', 'codigo'=>'11303', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Chile Chico', 'codigo'=>'11401', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Río Ibáñez', 'codigo'=>'11402', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Punta Arenas', 'codigo'=>'12101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Laguna Blanca', 'codigo'=>'12102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Río Verde', 'codigo'=>'12103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Gregorio', 'codigo'=>'12104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cabo de Hornos', 'codigo'=>'12201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Antártica', 'codigo'=>'12202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Porvenir', 'codigo'=>'12301', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Primavera', 'codigo'=>'12302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Timaukel', 'codigo'=>'12303', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Natales', 'codigo'=>'12401', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Torres del Paine', 'codigo'=>'12402', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Santiago', 'codigo'=>'13101', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cerrillos', 'codigo'=>'13102', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Cerro Navia', 'codigo'=>'13103', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Conchalí', 'codigo'=>'13104', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'El Bosque', 'codigo'=>'13105', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Estación Central', 'codigo'=>'13106', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Huechuraba', 'codigo'=>'13107', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Independencia', 'codigo'=>'13108', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'La Cisterna', 'codigo'=>'13109', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'La Florida', 'codigo'=>'13110', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'La Granja', 'codigo'=>'13111', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'La Pintana', 'codigo'=>'13112', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'La Reina', 'codigo'=>'13113', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Las Condes', 'codigo'=>'13114', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lo Barnechea', 'codigo'=>'13115', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lo Espejo', 'codigo'=>'13116', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lo Prado', 'codigo'=>'13117', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Macul', 'codigo'=>'13118', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Maipú', 'codigo'=>'13119', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Ñuñoa', 'codigo'=>'13120', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pedro Aguirre Cerda', 'codigo'=>'13121', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Peñalolén', 'codigo'=>'13122', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Providencia', 'codigo'=>'13123', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pudahuel', 'codigo'=>'13124', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quilicura', 'codigo'=>'13125', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Quinta Normal', 'codigo'=>'13126', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Recoleta', 'codigo'=>'13127', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Renca', 'codigo'=>'13128', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Joaquín', 'codigo'=>'13129', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Miguel', 'codigo'=>'13130', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Ramón', 'codigo'=>'13131', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Vitacura', 'codigo'=>'13132', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Puente Alto', 'codigo'=>'13201', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Pirque', 'codigo'=>'13202', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San José de Maipo', 'codigo'=>'13203', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Colina', 'codigo'=>'13301', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Lampa', 'codigo'=>'13302', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Tiltil', 'codigo'=>'13303', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Bernardo', 'codigo'=>'13401', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Buin', 'codigo'=>'13402', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Calera de Tango', 'codigo'=>'13403', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Paine', 'codigo'=>'13404', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Melipilla', 'codigo'=>'13501', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Alhué', 'codigo'=>'13502', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Curacaví', 'codigo'=>'13503', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'María Pinto', 'codigo'=>'13504', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'San Pedro', 'codigo'=>'13505', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Talagante', 'codigo'=>'13601', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'El Monte', 'codigo'=>'13602', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Isla de Maipo', 'codigo'=>'13603', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Padre Hurtado', 'codigo'=>'13604', 'activo'=>1]);
        Municipalidades::create(['nombre' => 'Peñaflor', 'codigo'=>'13605', 'activo'=>1]);        
    }
}
